GMAIL_USERNAME: email
GMAIL_PASSWORD: pass

ADMIN_NAME: name
ADMIN_EMAIL: email
ADMIN_PASSWORD: pass

MYUSA_OAUTH_PROVIDER_KEY: key
MYUSA_OAUTH_PROVIDER_SECRET: secret
MYUSA_HOME: https://my.usa.gov

ROLES: [admin, user, SME]


SALESFORCE_USERNAME: user
SALESFORCE_PASSWORD: pass
SALESFORCE_CLIENT_ID: id
SALESFORCE_CLIENT_SECRET: secret
SALESFORCE_SECURITY_TOKEN: token
SALESFORCE_HOST: host
SALESFORCE_APP_OBJECT: salesforce_obj__c