# Analysis and Creative Problem Solving:
# 	desc: Expertise determining user needs or identifying market opportunities and designing and deploying solutions;
# 	scores:
# 		- 
# (5) Applicant's ability to perform these tasks at a high level, as well as their team leadership, thought-leadership, writings, teachings, or appearances in these areas affirm that they are widely regarded as an expert in this subject area (20 pts)
 
# (4)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and shows evidence of significant contributions to a team or community environment such as leadership, promotion, or accolades (16pts)
 
# (3)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and ability to work effectively both independently and as a team or community member (12pts)
 
# (2)  Applicant's resume and portfolio demonstrate above-average proficiency in this area while working primarily as an individual rather than as part of a team  (8pts)
 
# (1) Applicant's resume and portfolio demonstrate basic understanding of best practices, or baseline proficiency in this competency (4pts)
 
# (0) Applicant’s resume and portfolio do not adequately demonstrate this competency (0pts)
 
 
# Technology Acumen
# Ability to translate business problems into technology solutions that draw on current and emergent tools and technologies; while likewise describing esoteric and highly technical solutions to non-technical stakeholders
 
# (5) Applicant's ability to perform these tasks at a high level, as well as their team leadership, thought-leadership, writings, teachings, or appearances in these areas affirm that they are widely regarded as an expert in this subject area (20 pts)
 
# (4)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and shows evidence of significant contributions to a team or community environment such as leadership, promotion, or accolades (16pts)
 
# (3)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and ability to work effectively both independently and as a team or community member (12pts)
 
# (2)  Applicant's resume and portfolio demonstrate above-average proficiency in this area while working primarily as an individual rather than as part of a team  (8pts)
 
# (1) Applicant's resume and portfolio demonstrate basic understanding of best practices, or baseline proficiency in this competency (4pts)
 
# (0) Applicant’s resume and portfolio do not adequately demonstrate this competency (0pts)
 
# Entrepreneurship and Product Management
# experience delivering products or services from concept to market
 
# (5) Applicant's ability to perform these tasks at a high level, as well as their team leadership, thought-leadership, writings, teachings, or appearances in these areas affirm that they are widely regarded as an expert in this subject area (20 pts)
 
# (4)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and shows evidence of significant contributions to a team or community environment such as leadership, promotion, or accolades (16pts)
 
# (3)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and ability to work effectively both independently and as a team or community member (12pts)
 
# (2)  Applicant's resume and portfolio demonstrate above-average proficiency in this area while working primarily as an individual rather than as part of a team  (8pts)
 
# (1) Applicant's resume and portfolio demonstrate basic understanding of best practices, or baseline proficiency in this competency (4pts)
 
# (0) Applicant’s resume and portfolio do not adequately demonstrate this competency (0pts)
 
 
# Approach and Methodology
# Expertise applying frameworks that emphasize delivery, iteration, quantitative and qualitative learnings, and responsiveness
 
# (5) Applicant's ability to perform these tasks at a high level, as well as their team leadership, thought-leadership, writings, teachings, or appearances in these areas affirm that they are widely regarded as an expert in this subject area (20 pts)
 
# (4)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and shows evidence of significant contributions to a team or community environment such as leadership, promotion, or accolades (16pts)
 
# (3)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and ability to work effectively both independently and as a team or community member (12pts)
 
# (2)  Applicant's resume and portfolio demonstrate above-average proficiency in this area while working primarily as an individual rather than as part of a team  (8pts)
 
# (1) Applicant's resume and portfolio demonstrate basic understanding of best practices, or baseline proficiency in this competency (4pts)
 
# (0) Applicant’s resume and portfolio do not adequately demonstrate this competency (0pts)
 
# Empathy and Emotional Intelligence
# Experience in client-facing roles, navigating bureaucracy,  business development, or delivering services with a strong user-facing or consumer-oriented element 
 
# (5) Applicant's ability to perform these tasks at a high level, as well as their team leadership, thought-leadership, writings, teachings, or appearances in these areas affirm that they are widely regarded as an expert in this subject area (20 pts)
 
# (4)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and shows evidence of significant contributions to a team or community environment such as leadership, promotion, or accolades (16pts)
 
# (3)  Applicant's resume and portfolio demonstrate mastery and deep understanding in this area, and ability to work effectively both independently and as a team or community member (12pts)
 
# (2)  Applicant's resume and portfolio demonstrate above-average proficiency in this area while working primarily as an individual rather than as part of a team  (8pts)
 
# (1) Applicant's resume and portfolio demonstrate basic understanding of best practices, or baseline proficiency in this competency (4pts)
 
# (0) Applicant’s resume and portfolio do not adequately demonstrate this competency (0pts)
 
 
# Tools and Execution
# Experience in design, development and deployment of solutions leveraging current and emergent technologies and best practices

# NOTE: “full stack” refers to individuals capable of working with both server-side and client-side technologies.  Typically individuals are proficient in working with databases, system infrastructure, applications or frameworks, and web, browser.
 
# (5) Applicant's ability to perform these tasks at a high level, as well as their team leadership, thought-leadership, writings, teachings, or appearances in these areas affirm that they are widely regarded as an expert in this subject area (20 pts)
 
# (4)  Applicant's resume and portfolio demonstrate mastery and deep understanding across a “full-stack” of current and emergent technologies, and displays leadership either as a manager, formal team lead, or open source project lead   (16pts)
 
# (3)  Applicant's resume and portfolio demonstrate mastery and deep understanding across a “full-stack” of current and emergent technologies and ability to work both independently and as a team member, including contributions to open-source (12pts)
 
# (2)  Applicant's resume and portfolio demonstrate above-average proficiency in this competency while working primarily as an individual rather than as part of a team  (8pts)
 
# (1) Applicant's resume and portfolio demonstrate basic understanding of best practices, or baseline proficiency in current and emergent technologies (4pts)
 
# (0) Applicant’s resume and portfolio do not adequately demonstrate ability to perform these tasks (0pts)